import {
  SiPython,
  SiReact,
  SiJavascript,
  SiPhp,
  SiCss3,
  SiHtml5,
  SiPostgresql,
  SiSupabase,
  SiConvex,
  SiGit,
  SiDocker,
  SiNodedotjs,
  SiTypescript,
  SiTailwindcss,
  SiFramer,
} from "react-icons/si";

export const TECHS = [
  { id: "python", label: "Python", Icon: SiPython, color: "#3776AB" },
  { id: "react", label: "React", Icon: SiReact, color: "#61DAFB" },
  { id: "javascript", label: "JavaScript", Icon: SiJavascript, color: "#F7DF1E" },
  { id: "php", label: "PHP", Icon: SiPhp, color: "#777BB4" },
  { id: "css3", label: "CSS3", Icon: SiCss3, color: "#1572B6" },
  { id: "html5", label: "HTML5", Icon: SiHtml5, color: "#E34F26" },
  { id: "postgresql", label: "PostgreSQL", Icon: SiPostgresql, color: "#4169E1" },
  { id: "supabase", label: "Supabase", Icon: SiSupabase, color: "#3ECF8E" },
  { id: "convex", label: "Convex", Icon: SiConvex, color: "#F6462E" },
  { id: "git", label: "Git", Icon: SiGit, color: "#F05032" },
  { id: "docker", label: "Docker", Icon: SiDocker, color: "#2496ED" },
  { id: "nodejs", label: "Node.js", Icon: SiNodedotjs, color: "#5FA04E" },
  { id: "typescript", label: "TypeScript", Icon: SiTypescript, color: "#3178C6" },
  { id: "tailwind", label: "Tailwind CSS", Icon: SiTailwindcss, color: "#06B6D4" },
  { id: "animation", label: "Animation", Icon: SiFramer, color: "#EF4444" },
];
